
[mobs]
	blacklist = []
	whitelist = []
	always_show_level = false
	show_level_when_looking_at = false
	exp_bonus_per_level = 0.1
	hidden_levels = []

[attributes]
	attribute_bonuses = [["minecraft:generic.movement_speed", 0.001], ["minecraft:generic.flying_speed", 0.001], ["minecraft:generic.attack_damage", 0.1], ["minecraft:generic.armor", 0.1], ["minecraft:generic.max_health", 0.1], ["autoleveling:monster.projectile_damage_bonus", 0.1], ["autoleveling:monster.explosion_damage_bonus", 0.1]]

[default_leveling_settings]
	starting_level = 1
	max_level = 100
	levels_per_distance = 0.001
	levels_per_deepness = 0.001
	random_level_bonus = 0
	levels_per_day = 0.0
	level_power_per_distance = 0.0
	level_power_per_deepness = 0.0

